# Generated by Django 5.2.7 on 2025-11-05 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_titles', to='rhcontrol.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('rg_issue_date', models.DateField(blank=True, null=True)),
                ('ctps_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ctps_series', models.CharField(blank=True, max_length=10, null=True)),
                ('ctps_issue_date', models.DateField(blank=True, null=True)),
                ('pis', models.CharField(blank=True, max_length=20, null=True)),
                ('ethnicity', models.CharField(blank=True, max_length=50, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_birthplace_code', models.CharField(blank=True, max_length=2, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('Analfabeto(a)', 'Analfabeto'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=22, null=True)),
                ('retirement_status', models.CharField(blank=True, choices=[('I', 'Por Idade'), ('T', 'Por Tempo de Contribuição'), ('N', 'Não recebe')], max_length=1, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('E', 'Separado(a)'), ('U', 'União Estável')], max_length=1, null=True)),
                ('is_pcd', models.CharField(blank=True, choices=[('S', 'Sim'), ('N', 'Não')], max_length=1, null=True)),
                ('disability_type', models.CharField(blank=True, choices=[('Física', 'Física'), ('Visual', 'Visual'), ('Auditiva', 'Auditiva'), ('Mental', 'Mental'), ('Intelectual', 'Intelectual'), ('Múltipla', 'Múltipla')], max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('address_num', models.CharField(blank=True, max_length=10, null=True)),
                ('complement', models.CharField(blank=True, max_length=50, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state_code', models.CharField(blank=True, max_length=2, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=9, null=True)),
                ('emergency_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100, null=True)),
                ('mobile_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_num', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_agency_code', models.CharField(blank=True, max_length=20, null=True)),
                ('account_type', models.CharField(blank=True, choices=[('Corrente', 'Corrente'), ('Poupança', 'Poupança'), ('Salário', 'Salário'), ('Conta Conjunta', 'Conta Conjunta')], max_length=25, null=True)),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Atual')),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_trial_contract', models.BooleanField(default=False)),
                ('is_first_job', models.BooleanField(default=False)),
                ('is_intermittent_contract', models.BooleanField(default=False)),
                ('uses_transport_voucher', models.BooleanField(default=False)),
                ('has_insalubrity_bonus', models.BooleanField(default=False)),
                ('has_danger_bonus', models.BooleanField(default=False)),
                ('admission_exam_date', models.DateField(blank=True, null=True)),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='Data da Demissão')),
                ('termination_reason', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo da Demissão')),
                ('is_foreign', models.BooleanField(default=False)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('naturalization_date', models.DateField(blank=True, null=True)),
                ('married_to_brazilian', models.BooleanField(default=False)),
                ('has_brazilian_children', models.BooleanField(default=False)),
                ('rne_number', models.CharField(blank=True, max_length=50, null=True)),
                ('rne_issuing_authority', models.CharField(blank=True, max_length=50, null=True)),
                ('rne_issue_date', models.DateField(blank=True, null=True)),
                ('is_cipa_member', models.BooleanField(default=False, verbose_name='Integrante da CIPA')),
                ('cipa_mandate_start_date', models.DateField(blank=True, null=True, verbose_name='Início do Mandato na CIPA')),
                ('cipa_mandate_end_date', models.DateField(blank=True, null=True, verbose_name='Fim do Mandato na CIPA')),
                ('cipa_role', models.CharField(blank=True, max_length=100, null=True, verbose_name='Título na CIPA')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_setor', to='rhcontrol.department', verbose_name='Setor')),
                ('job_title', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios_cargo', to='rhcontrol.jobtitle', verbose_name='Cargo')),
            ],
        ),
    ]
