# Generated by Django 5.2.7 on 2025-11-17 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtitle',
            old_name='salario_base',
            new_name='base_salary',
        ),
    ]
