# Generated by Django 5.2.7 on 2025-12-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0003_vacation'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacation',
            name='vacation_duration',
            field=models.IntegerField(default=0, help_text='Duração em dias'),
            preserve_default=False,
        ),
    ]
