# Generated by Django 5.2.9 on 2025-12-04 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0004_vacation_vacation_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacation',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Retorno'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='start_date',
            field=models.DateField(verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='vacation',
            name='vacation_duration',
            field=models.IntegerField(help_text='Duração em dias', verbose_name='Duração'),
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=200, verbose_name='Nome do Treinamento')),
                ('training_date', models.DateField(verbose_name='Data do Treinamento')),
                ('training_provider', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornecedor do Treinamento')),
                ('training_duration_hours', models.IntegerField(help_text='Duração em horas', verbose_name='Duração (horas)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='rhcontrol.employee')),
            ],
        ),
    ]
