# Generated by Django 5.2.9 on 2025-12-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0005_alter_vacation_end_date_alter_vacation_return_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_duration_hours',
            new_name='training_duration',
        ),
    ]
