# Generated by Django 5.2.9 on 2025-12-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0006_rename_training_duration_hours_training_training_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='account_num',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Conta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Corrente', 'Corrente'), ('Poupança', 'Poupança'), ('Salário', 'Salário'), ('Conta Conjunta', 'Conta Conjunta')], max_length=25, null=True, verbose_name='Tipo de Conta'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address_num',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='admission_exam_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data do Exame Admissional'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='arrival_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Chegada'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_agency_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Agência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade de Nascimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cipa_role',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Função na CIPA'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='complement',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ctps_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão da CTPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ctps_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número da CTPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ctps_series',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Série da CTPS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='disability_type',
            field=models.CharField(blank=True, choices=[('Física', 'Física'), ('Visual', 'Visual'), ('Auditiva', 'Auditiva'), ('Mental', 'Mental'), ('Intelectual', 'Intelectual'), ('Múltipla', 'Múltipla')], max_length=50, null=True, verbose_name='Tipo de Deficiência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Analfabeto(a)', 'Analfabeto'), ('Fundamental Incompleto', 'Fundamental Incompleto'), ('Fundamental Completo', 'Fundamental Completo'), ('Médio Incompleto', 'Médio Incompleto'), ('Médio Completo', 'Médio Completo'), ('Superior Incompleto', 'Superior Incompleto'), ('Superior Completo', 'Superior Completo'), ('Pós-graduação', 'Pós-graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=22, null=True, verbose_name='Nível de Escolaridade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do Contato de Emergência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone de Emergência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1, null=True, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_brazilian_children',
            field=models.BooleanField(default=False, verbose_name='Tem Filhos Brasileiros'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_danger_bonus',
            field=models.BooleanField(default=False, verbose_name='Recebe Adicional de Periculosidade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='has_insalubrity_bonus',
            field=models.BooleanField(default=False, verbose_name='Recebe Adicional de Insalubridade'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_first_job',
            field=models.BooleanField(default=False, verbose_name='Primeiro Emprego'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_foreign',
            field=models.BooleanField(default=False, verbose_name='É Estrangeiro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_intermittent_contract',
            field=models.BooleanField(default=False, verbose_name='Contrato Intermitente'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_pcd',
            field=models.BooleanField(default=False, verbose_name='Pessoa com Deficiência (PCD)'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_trial_contract',
            field=models.BooleanField(default=False, verbose_name='Contrato em Período de Experiência'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)'), ('E', 'Separado(a)'), ('U', 'União Estável')], max_length=1, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='married_to_brazilian',
            field=models.BooleanField(default=False, verbose_name='Casado com Brasileiro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mobile_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='mother_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome da Mãe'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='naturalization_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Naturalização'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pis',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PIS'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='retirement_status',
            field=models.CharField(blank=True, choices=[('I', 'Por Idade'), ('T', 'Por Tempo de Contribuição'), ('N', 'Não recebe')], max_length=1, null=True, verbose_name='Status de Aposentadoria'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do RG'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rne_issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão do RNE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rne_issuing_authority',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Autoridade Emissora do RNE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rne_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do RNE'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_birthplace_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF de Nascimento'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uses_transport_voucher',
            field=models.BooleanField(default=False, verbose_name='Usa Vale Transporte'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='zip_code',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP'),
        ),
    ]
