# Generated by Django 5.2.9 on 2025-12-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0007_alter_employee_account_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição do Treinamento'),
        ),
    ]
