# Generated by Django 5.2.9 on 2025-12-11 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0008_training_training_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.AddField(
            model_name='training',
            name='attended_employees',
            field=models.ManyToManyField(blank=True, related_name='attended_trainings', to='rhcontrol.employee', verbose_name='Funcionários Que Compareceram'),
        ),
        migrations.AddField(
            model_name='training',
            name='is_fundamental',
            field=models.BooleanField(default=False, verbose_name='É Treinamento Fundamental?'),
        ),
        migrations.AddField(
            model_name='training',
            name='scheduled_employees',
            field=models.ManyToManyField(blank=True, related_name='scheduled_trainings', to='rhcontrol.employee', verbose_name='Funcionários Previstos'),
        ),
        migrations.AddField(
            model_name='training',
            name='target_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rhcontrol.department', verbose_name='Setor Alvo (Se Fundamental)'),
        ),
        migrations.CreateModel(
            name='EmployeeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_changed', models.DateField(auto_now_add=True, verbose_name='Data da Mudança')),
                ('old_job_title', models.CharField(max_length=200, null=True, verbose_name='Cargo Anterior')),
                ('new_job_title', models.CharField(max_length=200, null=True, verbose_name='Novo Cargo')),
                ('old_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Salário Anterior')),
                ('new_salary', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Novo Salário')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='Motivo')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='rhcontrol.employee')),
            ],
        ),
    ]
