# Generated by Django 5.2.9 on 2026-01-29 13:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0009_remove_training_employee_training_attended_employees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeehistory',
            name='date_changed',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Mudança'),
        ),
    ]
