# Generated by Django 5.2.9 on 2026-01-29 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0013_alter_employee_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ethnicity',
            field=models.CharField(blank=True, choices=[('Branca', 'Branca'), ('Preta', 'Preta'), ('Parda', 'Parda'), ('Amarela', 'Amarela'), ('Indígena', 'Indígena')], max_length=10, null=True, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='RG'),
        ),
    ]
