# Generated by Django 5.2.9 on 2026-01-29 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0014_alter_employee_ethnicity_alter_employee_rg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
