# Generated by Django 5.2.9 on 2026-01-30 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0015_alter_employee_rg'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='has_dependents',
            field=models.BooleanField(default=False, verbose_name='Possui Dependentes'),
        ),
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('birth_date', models.DateField(verbose_name='Data de Nascimento')),
                ('relationship_type', models.CharField(choices=[('Filho(a)', 'Filho(a)'), ('Cônjuge', 'Cônjuge'), ('Pai/Mãe', 'Pai/Mãe'), ('Irmão(ã)', 'Irmão(ã)'), ('Outro', 'Outro')], max_length=10, verbose_name='Parentesco')),
                ('has_disability', models.BooleanField(default=False, verbose_name='Possui Deficiência')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='rhcontrol.employee')),
            ],
        ),
    ]
