# Generated by Django 5.2.9 on 2026-01-30 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0016_employee_has_dependents_dependent'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeehistory',
            name='new_cipa_role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIPA Nova'),
        ),
        migrations.AddField(
            model_name='employeehistory',
            name='old_cipa_role',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CIPA Anterior'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cipa_role',
            field=models.CharField(blank=True, choices=[('Titular', 'Titular'), ('Suplente', 'Suplente')], max_length=20, null=True, verbose_name='Função na CIPA'),
        ),
    ]
