# Generated by Django 5.2.9 on 2026-02-12 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0017_employeehistory_new_cipa_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='special_workday',
            field=models.CharField(blank=True, choices=[('12 X 36', '12 X 36'), ('24 X 72', '24 X 72'), ('Outro', 'Outro')], max_length=20, null=True, verbose_name='Trabalho Especial'),
        ),
        migrations.AddField(
            model_name='employee',
            name='workday_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Jornada'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_days',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Dias de Trabalho'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Horário de Trabalho'),
        ),
        migrations.AddField(
            model_name='employee',
            name='working_interval',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Intervalo de Trabalho'),
        ),
    ]
