# Generated by Django 5.2.9 on 2026-02-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0018_employee_special_workday_employee_workday_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='special_workday_other',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificação do Trabalho Especial'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='workday_type',
            field=models.CharField(blank=True, choices=[('F - Jornada de semana fixa', 'Fixa'), ('V - Jornada de semana variável', 'Variável')], max_length=50, null=True, verbose_name='Tipo de Jornada'),
        ),
    ]
