# Generated by Django 5.2.9 on 2026-02-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0019_employee_special_workday_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='working_days',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='working_interval',
        ),
        migrations.AddField(
            model_name='employee',
            name='working_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informações sobre a Jornada de Trabalho'),
        ),
    ]
