# Generated by Django 5.2.9 on 2026-02-13 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0020_remove_employee_working_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='registration_number',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Matrícula'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='working_info',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Informações sobre a Jornada de Trabalho (Dias, Horários e Intervalos)'),
        ),
    ]
