# Generated by Django 5.2.9 on 2026-02-19 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0021_employee_registration_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitle',
            name='description',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.CreateModel(
            name='FullAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_address', to='rhcontrol.employee')),
                ('address_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_address_num', to='rhcontrol.employee')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_city', to='rhcontrol.employee')),
                ('complement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_complement', to='rhcontrol.employee')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_neighborhood', to='rhcontrol.employee')),
                ('state_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_state_code', to='rhcontrol.employee')),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='full_zip_code', to='rhcontrol.employee')),
            ],
        ),
    ]
