# Generated by Django 5.2.9 on 2026-02-19 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0022_alter_jobtitle_description_fulladress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FullAdress',
        ),
    ]
