# Generated by Django 5.2.9 on 2026-02-23 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('rhcontrol', '0023_delete_fulladress'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('VACATION', 'Início de Férias'), ('TRAINING', 'Vencimento de Treinamento'), ('TRIAL_END', 'Fim do Contrato de Experiência'), ('EXAM_DUE', 'Exame Ocupacional a Vencer'), ('BIRTHDAY', 'Aniversário do Colaborador'), ('COMPANY_ANNIVERSARY', 'Aniversário de Empresa')], max_length=30, verbose_name='Tipo de Evento')),
                ('days_in_advance', models.PositiveIntegerField(default=15, verbose_name='Dias de Antecedência')),
                ('is_active', models.BooleanField(default=True, verbose_name='Regra Ativa')),
            ],
            options={
                'unique_together': {('event_type', 'days_in_advance')},
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome / Setor')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('receive_all_events', models.BooleanField(default=False, verbose_name='Recebe Todos os Eventos')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('subscribed_rules', models.ManyToManyField(blank=True, related_name='subscribers', to='rhcontrol.notificationrule', verbose_name='Regras Inscritas')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('reference_year', models.PositiveIntegerField(verbose_name='Ano de Referência do Evento')),
                ('recipients_snapshot', models.JSONField(default=list, help_text='Lista exata de e-mails que receberam esta notificação no momento do envio.', verbose_name='Destinatários (Snapshot)')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Enviado em')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='rhcontrol.employee')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logs', to='rhcontrol.notificationrule')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='rhcontrol_n_content_d5894b_idx'), models.Index(fields=['reference_year'], name='rhcontrol_n_referen_a7ba30_idx')],
                'unique_together': {('rule', 'content_type', 'object_id', 'reference_year')},
            },
        ),
    ]
