# Generated by Django 5.2.9 on 2026-02-26 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0024_notificationrule_notificationrecipient_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('VACATION', 'Início de Férias'), ('TRAINING', 'Vencimento de Treinamento'), ('TRIAL_END', 'Fim do Contrato de Experiência'), ('EXAM_DUE', 'Exame Ocupacional a Vencer'), ('BIRTHDAY', 'Aniversário do Colaborador'), ('COMPANY_ANNIVERSARY', 'Aniversário de Empresa'), ('CAREER_PLAN_REMINDER', 'Aviso de Promoção (30 dias)'), ('CAREER_PLAN_CANCELLED', 'Plano de Carreira Cancelado'), ('CAREER_PLAN_EFFECTIVE', 'Promoção Efetivada')], max_length=30, verbose_name='Tipo de Evento'),
        ),
        migrations.CreateModel(
            name='CareerPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salário Atual (Criação)')),
                ('proposed_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salário Proposto')),
                ('promotion_date', models.DateField(verbose_name='Data da Promoção')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Agendado'), ('AWAITING_CONFIRMATION', 'Aguardando Confirmação'), ('CONFIRMED', 'Confirmado'), ('EFFECTIVE', 'Efetivo'), ('CANCELLED', 'Cancelado')], default='SCHEDULED', max_length=40, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('effective_applied_at', models.DateTimeField(blank=True, null=True)),
                ('cancellation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_plans', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
                ('current_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rhcontrol.department', verbose_name='Setor Atual (Criação)')),
                ('current_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rhcontrol.jobtitle', verbose_name='Cargo Atual (Criação)')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_plans', to='rhcontrol.employee', verbose_name='Funcionário')),
                ('proposed_job', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='rhcontrol.jobtitle', verbose_name='Próximo Cargo')),
            ],
            options={
                'verbose_name': 'Plano de Carreira',
                'verbose_name_plural': 'Planos de Carreira',
                'constraints': [models.UniqueConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'AWAITING_CONFIRMATION', 'CONFIRMED'])), fields=('employee',), name='unique_active_career_plan')],
            },
        ),
    ]
