# Generated by Django 5.2.9 on 2026-03-03 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0026_alter_careerplan_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='training_duration',
            new_name='training_total_hours',
        ),
        migrations.RemoveField(
            model_name='training',
            name='training_date',
        ),
        migrations.AddField(
            model_name='training',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='training',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Início'),
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(verbose_name='Descrição')),
                ('occurrence_date', models.DateField(verbose_name='Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrencies', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='rhcontrol.employee')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['occurrence_date'],
            },
        ),
    ]
