# Generated by Django 5.2.9 on 2026-03-03 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0028_occurrence_add_attachment_and_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='attachment',
        ),
    ]
