# Generated by Django 5.2.9 on 2026-03-06 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0029_remove_occurrence_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAlertPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('vacation_start', 'Início de Férias'), ('training_due', 'Vencimento de Treinamento'), ('trial_end', 'Fim do Contrato de Experiência'), ('exam_due', 'Exame Ocupacional a Vencer'), ('birthday', 'Aniversário do Colaborador'), ('company_anniversary', 'Aniversário de Empresa'), ('career_plan_reminder', 'Aviso de Promoção (30 dias)'), ('career_plan_cancelled', 'Plano de Carreira Cancelado'), ('career_plan_effective', 'Promoção Efetivada')], max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'alert_type')},
            },
        ),
    ]
