# Generated by Django 5.2.9 on 2026-03-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0030_useralertpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='is_integration',
            field=models.BooleanField(default=False, help_text='Marque se este treinamento é padrão para novos funcionários.', verbose_name='Treinamento de Integração (Onboarding)?'),
        ),
        migrations.AlterField(
            model_name='notificationrule',
            name='event_type',
            field=models.CharField(choices=[('VACATION', 'Início de Férias'), ('TRAINING', 'Vencimento de Treinamento'), ('TRIAL_END', 'Fim do Contrato de Experiência'), ('EXAM_DUE', 'Exame Ocupacional a Vencer'), ('BIRTHDAY', 'Aniversário do Colaborador'), ('COMPANY_ANNIVERSARY', 'Aniversário de Empresa'), ('CAREER_PLAN_REMINDER', 'Aviso de Promoção'), ('CAREER_PLAN_CANCELLED', 'Plano de Carreira Cancelado'), ('CAREER_PLAN_EFFECTIVE', 'Promoção Efetivada')], max_length=30, verbose_name='Tipo de Evento'),
        ),
        migrations.AlterField(
            model_name='useralertpreference',
            name='alert_type',
            field=models.CharField(choices=[('vacation_start', 'Início de Férias'), ('training_due', 'Vencimento de Treinamento'), ('trial_end', 'Fim do Contrato de Experiência'), ('exam_due', 'Exame Ocupacional a Vencer'), ('birthday', 'Aniversário do Colaborador'), ('company_anniversary', 'Aniversário de Empresa'), ('career_plan_reminder', 'Aviso de Promoção'), ('career_plan_cancelled', 'Plano de Carreira Cancelado'), ('career_plan_effective', 'Promoção Efetivada')], max_length=30),
        ),
    ]
