# Generated by Django 5.2.9 on 2026-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0031_training_is_integration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='training_location_type',
            field=models.CharField(choices=[('Interno', 'Interno'), ('Externo', 'Externo')], default='Interno', max_length=10, verbose_name='Local do Treinamento'),
        ),
    ]
