# Generated by Django 5.2.9 on 2026-03-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0032_training_training_location_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Fim'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='is_absence',
            field=models.BooleanField(default=False, verbose_name='É um afastamento?'),
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='occurrence_date',
            field=models.DateField(verbose_name='Data da Ocorrência / Início'),
        ),
    ]
