# Generated by Django 5.2.9 on 2026-04-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0033_occurrence_end_date_occurrence_is_absence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código CID')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição Oficial')),
            ],
            options={
                'verbose_name': 'CID-10',
                'verbose_name_plural': 'CIDs-10',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='occurrence',
            name='cid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occurrences', to='rhcontrol.cid', verbose_name='CID-10 (Opcional)'),
        ),
    ]
