# Generated by Django 5.2.9 on 2026-04-16 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rhcontrol', '0034_cid_occurrence_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fim do Contrato (Prazo Determinado)'),
        ),
    ]
